import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { toast } from "react-toastify";
import { getHeader } from "../../../../components/pdf/pdfHeader";
import { getFooter } from "../../../../components/pdf/pdfFooter";
import { buildOutsideDispensePdfData, escapeHtml } from "./outsideDispensePdfUtils";

const renderToCanvas = async (html, width = 794) => {
    const el = document.createElement("div");
    el.style.position = "absolute";
    el.style.left = "-9999px";
    el.style.top = "0";
    el.style.width = `${width}px`;
    el.style.background = "#fff";
    el.style.fontFamily = "Arial, Helvetica, sans-serif";
    el.style.color = "#000";
    el.innerHTML = `
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
    ${html}
  `;
    document.body.appendChild(el);
    await new Promise((r) => setTimeout(r, 500));
    const canvas = await html2canvas(el, {
        scale: 2.5,
        useCORS: true,
        backgroundColor: "#ffffff",
        windowWidth: width,
        windowHeight: el.scrollHeight,
    });
    document.body.removeChild(el);
    return canvas;
};

export const handleOutsideDownload = async (record) => {
    if (!record) {
        toast.error("No outside dispense data found");
        return;
    }

    try {
        const { customer, invoice, generatedBy, grandTotalStr, amountInWords, medicinesRows } =
            buildOutsideDispensePdfData(record);

        const headerHtml = `<div style="width:794px; box-sizing:border-box; padding:15px 15px 0;">${getHeader()}</div>`;
        const footerHtml = `<div style="width:794px; box-sizing:border-box; padding:0 15px 15px;">${getFooter()}</div>`;

        const bodyHtml = `
      <div style="width:794px; box-sizing:border-box; padding:0 15px; font-family:Arial, Helvetica, sans-serif; color:#000; background:#fff;">
        <div style="display:flex; border:1px solid #000; margin:10px 0; font-size:13px;">
          <div style="width:65%; background:#f9f5f0; padding:12px; border-right:1px solid #000;">
            <table style="width:100%; margin-top:30px;">
              <tr><td style="font-weight:bold; width:110px;">Customer Name</td><td>:</td><td>${escapeHtml(customer.name)}</td></tr>
              <tr><td style="font-weight:bold;">Age</td><td>:</td><td>${customer.age !== "" ? escapeHtml(String(customer.age)) : "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Phone</td><td>:</td><td>${escapeHtml(customer.phone) || "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Alternative No.</td><td>:</td><td>${escapeHtml(customer.alternativePhone) || "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Email</td><td>:</td><td>${escapeHtml(customer.email) || "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Address</td><td>:</td><td>${escapeHtml(customer.address) || "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Disease</td><td>:</td><td>${escapeHtml(customer.disease) || "N/A"}</td></tr>
              <tr><td style="font-weight:bold;">Generated By</td><td>:</td><td>${escapeHtml(generatedBy)}</td></tr>
            </table>
          </div>
          <div style="width:35%; background:#f9f5f0; padding:12px;">
            <div style="text-align:center; font-weight:bold; font-size:17px; margin-bottom:10px; border-bottom:1px solid #000; padding-bottom:6px;">
              OUTSIDE DISPENSE
            </div>
            <table style="width:100%;">
              <tr><td style="font-weight:bold; width:70px;">No</td><td style="width:10px;">:</td><td>${escapeHtml(invoice.no)}</td></tr>
              <tr><td style="font-weight:bold;">Date / Time</td><td>:</td><td style="white-space:nowrap;">${invoice.date} @ ${invoice.time}</td></tr>
              <tr><td style="font-weight:bold;">Dispensed By</td><td>:</td><td>${escapeHtml(invoice.dispensedBy)}</td></tr>
            </table>
            <div style="margin-top:8px; margin-bottom:10px; font-size:11px;">
              <span style="font-weight:bold;">Status:</span>
              <span style="margin-left:6px; font-size:14px; font-weight:900; border-radius:4px; display:inline-block; padding:2px 8px;">
                Dispensed
              </span>
            </div>
          </div>
        </div>

        <table style="width:100%; border-collapse:collapse; margin:16px 0; font-size:11px;">
          <thead>
            <tr style="background:#f5f5f5;">
              <th style="border:1px solid #000; padding:6px; width:45px;">Srl</th>
              <th style="border:1px solid #000; padding:6px;">Medicine Name</th>
              <th style="border:1px solid #000; padding:6px; width:60px;">Qty</th>
              <th style="border:1px solid #000; padding:6px; width:85px;">Rate</th>
              <th style="border:1px solid #000; padding:6px; width:85px;">Total</th>
            </tr>
          </thead>
          <tbody>${medicinesRows}</tbody>
        </table>

        <div style="display:flex; margin-top:15px; padding-top:10px; margin-bottom:10px;">
          <div style="width:55%; padding-right:15px;">
            <div style="font-weight:bold; font-size:13px; margin-bottom:6px;">Amount in Words:</div>
            <div style="font-style:italic; font-size:12px;">${escapeHtml(amountInWords)}</div>
          </div>
          <div style="width:45%; font-size:12px;">
            <div style="display:flex; justify-content:space-between; font-size:14px; font-weight:bold; border-top:2px solid #000; padding-top:8px; margin-top:8px;">
              <span>TOTAL PAYABLE:</span><span>₹${grandTotalStr}</span>
            </div>
          </div>
        </div>
      </div>
    `;

        const [headerCanvas, footerCanvas, bodyCanvas] = await Promise.all([
            renderToCanvas(headerHtml),
            renderToCanvas(footerHtml),
            renderToCanvas(bodyHtml),
        ]);

        const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
        const pdfW = pdf.internal.pageSize.getWidth();
        const pdfH = pdf.internal.pageSize.getHeight();
        const margin = 10;
        const contentW = pdfW - margin * 2;

        const pxToMm = (canvas) => (canvas.height / canvas.width) * contentW;
        const headerH = pxToMm(headerCanvas);
        const footerH = pxToMm(footerCanvas);
        const bodyTotalH = pxToMm(bodyCanvas);
        const topPad = 5;
        const botPad = 5;
        const bodyAreaH = pdfH - headerH - footerH - topPad - botPad;
        const headerImg = headerCanvas.toDataURL("image/png");
        const footerImg = footerCanvas.toDataURL("image/png");
        const totalPages = Math.ceil(bodyTotalH / bodyAreaH);

        for (let page = 0; page < totalPages; page++) {
            if (page > 0) pdf.addPage();
            pdf.addImage(headerImg, "PNG", margin, 0, contentW, headerH);

            const bodyY = headerH + topPad;
            const srcYPx = ((page * bodyAreaH) / bodyTotalH) * bodyCanvas.height;
            const srcHPx = Math.min(
                (bodyAreaH / bodyTotalH) * bodyCanvas.height,
                bodyCanvas.height - srcYPx
            );

            const sliceCanvas = document.createElement("canvas");
            sliceCanvas.width = bodyCanvas.width;
            sliceCanvas.height = Math.round(srcHPx);
            const ctx = sliceCanvas.getContext("2d");
            ctx.drawImage(
                bodyCanvas,
                0,
                Math.round(srcYPx),
                bodyCanvas.width,
                Math.round(srcHPx),
                0,
                0,
                bodyCanvas.width,
                Math.round(srcHPx)
            );

            const sliceImgData = sliceCanvas.toDataURL("image/png");
            const sliceH = (sliceCanvas.height / sliceCanvas.width) * contentW;
            pdf.addImage(sliceImgData, "PNG", margin, bodyY, contentW, sliceH);

            const footerY = pdfH - footerH;
            pdf.addImage(footerImg, "PNG", margin, footerY, contentW, footerH);
            pdf.setFontSize(8);
            pdf.setTextColor(150);
            pdf.text(`Page ${page + 1} of ${totalPages}`, pdfW / 2, pdfH - 2, { align: "center" });
        }

        pdf.save(`Outside_Dispense_${invoice.no.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`);
        toast.success("Outside dispense PDF downloaded successfully");
    } catch (err) {
        console.error("Outside dispense PDF error:", err);
        toast.error("Failed to generate outside dispense PDF");
    }
};
