import { getFooter } from "../../../../components/pdf/pdfFooter";
import { pdfPrHeader } from "../../../../components/pdf/pdfPrHeader";
import { buildOutsideDispensePdfData, escapeHtml } from "./outsideDispensePdfUtils";

export const handleOutsidePrint = (record) => {
    if (!record) {
        alert("No outside dispense data found");
        return;
    }

    try {
        const { customer, invoice, generatedBy, grandTotalStr, amountInWords, medicinesRowsPrint } =
            buildOutsideDispensePdfData(record);

        const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Outside Dispense - Utpala Ayurdhama</title>
      <meta charset="UTF-8">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: Arial, Helvetica, sans-serif;
          font-size: 12px;
          margin: 0 auto;
          padding: 0;
          color: #000;
          max-width: 50rem;
          width: 100%;
        }
        .report-container { width: 100%; border-collapse: collapse; }
        .report-header { display: table-header-group; }
        .report-footer {
          position: fixed;
          bottom: 0;
          left: 0;
          right: 0;
          max-width: 50rem;
          width: 100%;
          margin: 0 auto;
          background: white;
          z-index: 10;
        }
        .footer-spacer { height: 180px; }
        .main-content { padding: 15px; width: 100%; }
        .info-container { display: flex; border: 1px solid #000; margin: 10px 0; }
        .patient-box {
          width: 65%;
          background: #fafafa;
          padding: 12px;
          border-right: 1px solid #000;
        }
        .receipt-box { width: 35%; background: #fafafa; }
        .receipt-title {
          text-align: center;
          font-weight: bold;
          font-size: 18px;
          border-bottom: 1px solid #000;
          padding: 8px;
          background: #f5f0eb;
        }
        .info-table { width: 100%; font-size: 12px; }
        .info-table td { padding: 5px 8px; }
        .info-table .label { font-weight: bold; width: 100px; }
        .items-table {
          width: 100%;
          border-collapse: collapse;
          margin: 16px 0;
          font-size: 11px;
        }
        .items-table th, .items-table td { border: 1px solid #000; padding: 6px; }
        .items-table th {
          background: #f5f5f5;
          font-weight: bold;
          text-align: center;
        }
        @media print {
          body { border: none; margin: 0; width: 100%; max-width: none; }
          .report-header { display: table-header-group; }
          .report-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            max-width: 100%;
            width: 100%;
            margin: 0 auto;
          }
        }
      </style>
    </head>
    <body>
      <table class="report-container">
        <thead>
          <tr>
            <td class="report-header">${pdfPrHeader()}</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <div class="main-content">
                <div class="info-container">
                  <div class="patient-box">
                    <table class="info-table">
                      <tr><td class="label">Customer Name</td><td>:</td><td>${escapeHtml(customer.name)}</td></tr>
                      <tr><td class="label">Age</td><td>:</td><td>${customer.age !== "" ? escapeHtml(String(customer.age)) : "N/A"}</td></tr>
                      <tr><td class="label">Phone</td><td>:</td><td>${escapeHtml(customer.phone) || "N/A"}</td></tr>
                      <tr><td class="label">Email</td><td>:</td><td>${escapeHtml(customer.email) || "N/A"}</td></tr>
                      <tr><td class="label">Disease</td><td>:</td><td>${escapeHtml(customer.disease) || "N/A"}</td></tr>
                      <tr><td class="label">Generated By</td><td>:</td><td>${escapeHtml(generatedBy)}</td></tr>
                    </table>
                  </div>
                  <div class="receipt-box">
                    <div class="receipt-title">OUTSIDE DISPENSE</div>
                    <table class="info-table" style="margin-top:8px;">
                      <tr><td class="label">Invoice No.</td><td>:</td><td>${escapeHtml(String(invoice.no))}</td></tr>
                      <tr><td class="label">Date / Time</td><td>:</td><td style="white-space:nowrap;">${invoice.date} @ ${invoice.time}</td></tr>
                      <tr><td class="label">Dispensed By</td><td>:</td><td>${escapeHtml(invoice.dispensedBy)}</td></tr>
                    </table>
                    <div style="margin:8px 8px 0; font-size:11px;">
                      <span style="font-weight:bold;">Status:</span>
                      <span style="margin-left:6px; font-weight:700; border-radius:4px; display:inline-block; padding:2px 8px;">
                        Dispensed
                      </span>
                    </div>
                  </div>
                </div>

                <table class="items-table">
                  <thead>
                    <tr>
                      <th style="width: 8%">Srl</th>
                      <th style="width: 52%">Medicine Name</th>
                      <th style="width: 10%">Qty</th>
                      <th style="width: 15%">Rate (₹)</th>
                      <th style="width: 15%">Total (₹)</th>
                    </tr>
                  </thead>
                  <tbody>${medicinesRowsPrint}</tbody>
                </table>

                <div style="display:flex; margin-top:15px; padding-top:10px; margin-bottom:10px;">
                  <div style="width:55%; padding-right:15px;">
                    <div style="font-weight:bold; font-size:13px; margin-bottom:6px;">Amount in Words:</div>
                    <div style="font-style:italic; font-size:12px;">${escapeHtml(amountInWords)}</div>
                  </div>
                  <div style="width:45%; font-size:12px;">
                    <div style="display:flex; justify-content:space-between; font-size:14px; font-weight:bold; border-top:2px solid #000; padding-top:8px; margin-top:8px;">
                      <span>TOTAL PAYABLE:</span><span>₹${grandTotalStr}</span>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
        <tfoot>
          <tr><td><div class="footer-spacer"></div></td></tr>
        </tfoot>
      </table>

      <div class="report-footer">${getFooter()}</div>

      <script>
        window.onload = function() {
          setTimeout(function() { window.print(); }, 300);
          window.onafterprint = function() {
            setTimeout(function() {
              if (window.opener && !window.opener.closed) window.close();
            }, 1000);
          };
        };
      </script>
    </body>
    </html>
    `;

        const printWindow = window.open("", "_blank", "width=1000,height=800,scrollbars=yes,resizable=yes");
        if (printWindow) {
            printWindow.document.write(html);
            printWindow.document.close();
            printWindow.focus();
        } else {
            alert("Popup blocked! Please allow popups to print the document.");
        }
    } catch (error) {
        console.error("Outside dispense print error:", error);
        alert("Failed to print outside dispense. Please try again.");
    }
};
